name: firebase_testv2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.3'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: 1.18.0
  cloud_firestore: 3.1.18
  google_fonts: 3.0.1
  lazy_load_scrollview: 1.3.0
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_bloc: 8.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
