name: firebase_testv2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: 1.18.0
  cloud_firestore: 3.1.18
  google_fonts: 3.0.1
  lazy_load_scrollview: 1.3.0
  firebase_storage: ^10.2.18
  json_annotation: 4.3.0
  json_serializable: 6.0.1
  rxdart: ^0.27.4
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_bloc: 8.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true