// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxMou97o9UeliQxjRxPp3J-H8rS4luEEU',
    appId: '1:168666715608:web:eacace7f3843c04264cead',
    messagingSenderId: '168666715608',
    projectId: 'iceman-test-edb49',
    authDomain: 'iceman-test-edb49.firebaseapp.com',
    storageBucket: 'iceman-test-edb49.appspot.com',
    measurementId: 'G-ZPZSCCDXGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEV92rzGGvhYC-FyCxENMcaWQ7_4imqSs',
    appId: '1:168666715608:android:031737e8f235231364cead',
    messagingSenderId: '168666715608',
    projectId: 'iceman-test-edb49',
    storageBucket: 'iceman-test-edb49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbUvQznZFFExsRrA3YJYNdoh47D1ZRUmY',
    appId: '1:168666715608:ios:4baac4962c8c93f864cead',
    messagingSenderId: '168666715608',
    projectId: 'iceman-test-edb49',
    storageBucket: 'iceman-test-edb49.appspot.com',
    iosClientId: '168666715608-n5olai30ki3lh3n2qg4utfh7pk2vh40i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
